//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Itens = new HashSet<Itens>();
        }
    
        public int CodigoDoCliente { get; set; }
        public string NomeCFC { get; set; }
        public string NomeCompletoDoCliente { get; set; }
        public string TipoDePessoaDoCliente { get; set; }
        public string CPFCNPJDoCliente { get; set; }
        public string EnderecoDoCliente { get; set; }
        public string NumeroDoCliente { get; set; }
        public string ComplementoDoCliente { get; set; }
        public string BairroDoCliente { get; set; }
        public int CodigoDaCidade { get; set; }
        public int CodigoDoEstado { get; set; }
        public string CEPDoCliente { get; set; }
        public string EmailDoCliente { get; set; }
        public string SenhaDoCliente { get; set; }
        public string TelefoneResidencialDoCliente { get; set; }
        public string TelefoneCelularDoCliente { get; set; }
        public bool ClienteAtivo { get; set; }
        public string ObservacoesDoCliente { get; set; }
        public Nullable<System.DateTime> DataDoCadastro { get; set; }
        public string Foto1 { get; set; }
        public string Foto2 { get; set; }
        public string Foto3 { get; set; }
        public string Foto4 { get; set; }
        public bool SepararVeiculos { get; set; }
    
        public virtual Cidades Cidades { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itens> Itens { get; set; }
    }
}
