//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cfcadminEntities : DbContext
    {
        public cfcadminEntities()
            : base("name=cfcadminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cidades> Cidades { get; set; }
        public virtual DbSet<Configuracoes> Configuracoes { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Fornecedores> Fornecedores { get; set; }
        public virtual DbSet<Historicos> Historicos { get; set; }
        public virtual DbSet<Itens> Itens { get; set; }
        public virtual DbSet<OrdemDeServico> OrdemDeServico { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<DadosDoSinistro> DadosDoSinistro { get; set; }
        public virtual DbSet<Sinistros> Sinistros { get; set; }
        public virtual DbSet<Movimentacao> Movimentacao { get; set; }
        public virtual DbSet<Demonstrativo> Demonstrativo { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
    }
}
