//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demonstrativo
    {
        public int CodigoDoDemonstrativo { get; set; }
        public int CodigoDaMovimentacao { get; set; }
        public string TituloDoGrupo { get; set; }
        public string ItemReferencia { get; set; }
        public string ItemDescricao { get; set; }
        public Nullable<decimal> ItemValor { get; set; }
    }
}
