//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedores
    {
        public int CodigoDoFornecedor { get; set; }
        public string NomeDoFornecedor { get; set; }
        public string RazaoSocial { get; set; }
        public string CPFCNPJ { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Telefone { get; set; }
        public string TipoDoFornecedor { get; set; }
        public bool Ativo { get; set; }
    }
}
