//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itens()
        {
            this.Sinistros = new HashSet<Sinistros>();
        }
    
        public int CodigoDoItem { get; set; }
        public int CodigoDocliente { get; set; }
        public string DescricaoDoModelo { get; set; }
        public string Placa1DoVeiculo { get; set; }
        public string Placa2DoVeiculo { get; set; }
        public string Renavam { get; set; }
        public string NumeroDoChassi { get; set; }
        public string AnoDeFabricacao { get; set; }
        public string AnoDoModelo { get; set; }
        public string CorPredominante { get; set; }
        public bool Particular { get; set; }
        public string ObservacaoDoItem { get; set; }
        public Nullable<System.DateTime> DataDoCadastro { get; set; }
        public Nullable<System.DateTime> DataDaDesativacao { get; set; }
        public string CodigoFipe { get; set; }
        public int CodigoDoTipo { get; set; }
        public string Foto1 { get; set; }
        public string Foto2 { get; set; }
        public string Foto3 { get; set; }
        public string Foto4 { get; set; }
        public Nullable<System.DateTime> DataDaAtivacao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string DescricaoDaMarca { get; set; }
    
        public virtual Tipos Tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinistros> Sinistros { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
