//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int CodigoDoTitulo { get; set; }
        public string DescricaoDoTitulo { get; set; }
        public Nullable<int> CodigoDoCliente { get; set; }
        public string TipoDoTitulo { get; set; }
        public decimal ValorDoTitulo { get; set; }
        public System.DateTime DataDoTitulo { get; set; }
        public System.DateTime DataDoVencimento { get; set; }
        public Nullable<System.DateTime> DataDoRecebimento { get; set; }
        public string NossoNumero { get; set; }
        public string TipoDaBaixa { get; set; }
        public bool GeradoBoleto { get; set; }
        public bool GeradoRemessa { get; set; }
        public string Observacao1 { get; set; }
        public string Observacao2 { get; set; }
        public string Observacao3 { get; set; }
        public bool Cancelado { get; set; }
        public Nullable<int> NumeroParcela { get; set; }
        public Nullable<int> TotalParcelas { get; set; }
        public bool BoletoAdmin { get; set; }
        public bool Credito { get; set; }
        public bool Debito { get; set; }
        public Nullable<int> CodigoDoSinistro { get; set; }
        public Nullable<int> CodigoDoFornecedor { get; set; }
        public bool Boleto { get; set; }
        public bool Caixa { get; set; }
        public string Detalhes { get; set; }
        public int CodigoDoHistorico { get; set; }
        public string Foto1 { get; set; }
        public string Foto2 { get; set; }
        public string Foto3 { get; set; }
        public string Foto4 { get; set; }
        public bool Rateio { get; set; }
    
        public virtual Historicos Historicos { get; set; }
    }
}
