//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemDeServico
    {
        public int CodigoDaOS { get; set; }
        public int CodigoDoTitulo { get; set; }
        public string Mensagem { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public int NovoTitulo { get; set; }
    }
}
