//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinistros
    {
        public int CodigoDoSinistro { get; set; }
        public int CodigoDoItem { get; set; }
        public int CodigoDoCliente { get; set; }
        public decimal ValorDoSinistro { get; set; }
        public Nullable<System.DateTime> DataDoSinistro { get; set; }
        public Nullable<System.DateTime> DataDeConclusaoDoSinistro { get; set; }
        public string ObservacaoDoSinistro { get; set; }
        public Nullable<decimal> CotasNaData { get; set; }
        public Nullable<decimal> ValorPorCota { get; set; }
        public Nullable<int> ClientesNoRateio { get; set; }
        public Nullable<decimal> ValorDeReferencia { get; set; }
        public Nullable<System.DateTime> DataDoFaturamento { get; set; }
        public string Foto1 { get; set; }
        public string Foto2 { get; set; }
        public string Foto3 { get; set; }
        public string Foto4 { get; set; }
        public string Foto5 { get; set; }
        public string Foto6 { get; set; }
        public string Foto7 { get; set; }
        public string Foto8 { get; set; }
    
        public virtual Itens Itens { get; set; }
    }
}
