//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public bool AtivaSite { get; set; }
        public bool AtivaBanner { get; set; }
        public bool AtivaCobertura { get; set; }
        public bool AtivaServicos { get; set; }
        public bool AtivaVeiculos { get; set; }
        public bool AtivaLogin { get; set; }
        public bool AtivaSobre { get; set; }
        public bool AtivaContato { get; set; }
        public string SobreTitulo { get; set; }
        public string SobreResumo { get; set; }
        public string VeiculosTexto { get; set; }
        public string CoberturaTexto { get; set; }
        public string PrecoTexto { get; set; }
        public string ServicosTexto { get; set; }
        public string Area1Titulo { get; set; }
        public string Area1Texto { get; set; }
        public string Area2Titulo { get; set; }
        public string Area2Texto { get; set; }
        public string Depoimento1Cliente { get; set; }
        public string Depoimento1Texto { get; set; }
        public string Depoimento2Cliente { get; set; }
        public string Depoimento2Texto { get; set; }
        public string Depoimento3Cliente { get; set; }
        public string Depoimento3Texto { get; set; }
        public string Depoimento4Cliente { get; set; }
        public string Depoimento4Texto { get; set; }
        public bool AtivaDepoimento { get; set; }
        public string Contador1Titulo { get; set; }
        public Nullable<int> Contador1Numero { get; set; }
        public string Contador2Titulo { get; set; }
        public Nullable<int> Contador2Numero { get; set; }
        public string Contador3Titulo { get; set; }
        public Nullable<int> Contador3Numero { get; set; }
        public string Contador4Titulo { get; set; }
        public Nullable<int> Contador4Numero { get; set; }
        public bool AtivaParceiros { get; set; }
        public string Telefone { get; set; }
        public string Endereco { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Email { get; set; }
        public string Banner1Texto1 { get; set; }
        public string Banner1Texto2 { get; set; }
        public string Banner1Imagem { get; set; }
        public bool AtivaBanner1Padrao { get; set; }
        public bool AtivaBanner2Padrao { get; set; }
        public string Banner2Texto1 { get; set; }
        public string Banner2Texto2 { get; set; }
        public string Banner2Texto3 { get; set; }
        public string Banner2Imagem { get; set; }
        public int CodigoDoSite { get; set; }
        public string SobreTexto { get; set; }
        public string SobreImagem { get; set; }
        public bool AtivaPreco { get; set; }
        public bool AtivaContador { get; set; }
        public string SobreImagemEquipe { get; set; }
        public bool AtivaArea { get; set; }
        public bool AtivaLinks { get; set; }
    }
}
