//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titulos
    {
        public int CodigoDoTitulo { get; set; }
        public string DescricaoDoTitulo { get; set; }
        public int CodigoDoCliente { get; set; }
        public string TipoDoTitulo { get; set; }
        public decimal ValorDoTitulo { get; set; }
        public System.DateTime DataDoTitulo { get; set; }
        public System.DateTime DataDoVencimento { get; set; }
        public Nullable<System.DateTime> DataDoRecebimento { get; set; }
        public string NossoNumero { get; set; }
        public string TipoDaBaixa { get; set; }
        public bool GeradoBoleto { get; set; }
        public bool GeradoRemessa { get; set; }
        public string Observacao1 { get; set; }
        public string Observacao2 { get; set; }
        public string Observacao3 { get; set; }
        public bool Cancelado { get; set; }
        public int CodigoDaConta { get; set; }
        public bool EmailEnviado { get; set; }
        public Nullable<int> NumeroParcela { get; set; }
        public Nullable<int> TotalParcelas { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
